// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.exc.domain;

import com.exc.domain.ExchangeCurrency;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ExchangeCurrency_Roo_Configurable {
    
    declare @type: ExchangeCurrency: @Configurable;
    
}
